-- Temporarily disable RLS for testing
ALTER TABLE Course DISABLE ROW LEVEL SECURITY;
ALTER TABLE Lesson DISABLE ROW LEVEL SECURITY;
ALTER TABLE Teacher DISABLE ROW LEVEL SECURITY;
ALTER TABLE Student DISABLE ROW LEVEL SECURITY;
